# theme: minima
remote_theme: pages-themes/architect@v0.2.0
plugins:
jekyll-remote-theme # add this line to the plugins list if you already have one

title: Learn gitHub Pages
author: Marco Combetto
description: test

show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
