remote_theme: pages-themes/slate@v0.2.0
url: "https://www.marcocombetto.com"
baseurl: ""
plugins:
  - jekyll-remote-theme
title: "Marco Combetto"
description: "AI &amp; Digital Transformation — Public Sector · AI Act · Data Science"
