remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme

title: ""          # hides “marcomb.github.io”
author: Marco Combetto

# show_downloads: false ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [G-XZ5Z381EJQ]
